name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download ngrok
        run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip

      - name: Extract ngrok
        run: unzip ngrok.zip

      - name: Authenticate ngrok
        run: |
          ./ngrok/ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Install SSH server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server

      - name: Set Password for runneradmin
        run: |
          echo 'runneradmin:P@ssw0rd!' | sudo chpasswd
          sudo usermod -aG sudo runneradmin

      - name: Create ngrok Tunnel
        run: |
          ./ngrok/ngrok tcp 22
